### ISSUE TITLE
v5.0.0.1 

### ISSUE THREAD

**Issue by laakie** [Crypto-Currency/LitecoinPlus#84]
After updating to v5.0.0.1.
Encountering error on starting wallet.

******* exception encountered *******
./litecoinplusd(_Z13LogStackTracev+0x3c)[0x5dafac]
./litecoinplusd(_ZN11CDataStream4readEPci+0xe6)[0x4afb56]
./litecoinplusd(_ZN6CBlkDB18LoadBlockIndexGutsEv+0x124f)[0x4d77bf]
./litecoinplusd(_ZN6CBlkDB14LoadBlockIndexEv+0x2f)[0x4daebf]
./litecoinplusd(_Z14LoadBlockIndexb+0x105)[0x52fda5]
./litecoinplusd(_Z8AppInit2v+0x310b)[0x4f6d8b]
./litecoinplusd(_Z7AppInitiPPc+0x6c5)[0x4f99b5]
./litecoinplusd(main+0x2a)[0x4a515a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f1b89025f45]
./litecoinplusd[0x4a968f]

**Comment by typhoonsimon** [comment]
Hi, sorry I completely missed this. This error is wanted, it uses a controlled exception to test whether the blkindex.dat is new or not. If is not, it will upgrade to a new version (adding some key/value pairs). If you noted, this error will not appear anymore once the files are updated. Cheers
